#!/usr/bin/env python
from simple_tem import TEMClient

import argparse
import os
os.environ['PYTHONINSPECT'] = 'TRUE' #force interactive mode
parser = argparse.ArgumentParser()
parser.add_argument("host")
parser.add_argument("-p", "--port", default = 3535)
args = parser.parse_args()
c = TEMClient(args.host, args.port)